// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8EB1-likJI9qiYgK8e7TtnK-p5qI7MeE',
    appId: '1:14839235089:web:e3a5bac8b83e21da80e7b0',
    messagingSenderId: '14839235089',
    projectId: 'ec-carwash-app',
    authDomain: 'ec-carwash-app.firebaseapp.com',
    storageBucket: 'ec-carwash-app.firebasestorage.app',
    measurementId: 'G-R6E9CNL6MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStf8IOOAoeYGX81-SsvkQyP4m1qBr7Fs',
    appId: '1:14839235089:android:82dcc99e3ac5651280e7b0',
    messagingSenderId: '14839235089',
    projectId: 'ec-carwash-app',
    storageBucket: 'ec-carwash-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgp048LeiiwwWIZjWsemYvVDi7GORDFe8',
    appId: '1:14839235089:ios:3d56a72d455f4d4d80e7b0',
    messagingSenderId: '14839235089',
    projectId: 'ec-carwash-app',
    storageBucket: 'ec-carwash-app.firebasestorage.app',
    androidClientId: '14839235089-33m155i3in5li8i50dpo2l5fd1if8gsm.apps.googleusercontent.com',
    iosClientId: '14839235089-efeapvnup5cl59u5nu18nas95ku469k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecCarwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgp048LeiiwwWIZjWsemYvVDi7GORDFe8',
    appId: '1:14839235089:ios:3d56a72d455f4d4d80e7b0',
    messagingSenderId: '14839235089',
    projectId: 'ec-carwash-app',
    storageBucket: 'ec-carwash-app.firebasestorage.app',
    androidClientId: '14839235089-33m155i3in5li8i50dpo2l5fd1if8gsm.apps.googleusercontent.com',
    iosClientId: '14839235089-efeapvnup5cl59u5nu18nas95ku469k7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecCarwash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8EB1-likJI9qiYgK8e7TtnK-p5qI7MeE',
    appId: '1:14839235089:web:cd2387a3a818c57680e7b0',
    messagingSenderId: '14839235089',
    projectId: 'ec-carwash-app',
    authDomain: 'ec-carwash-app.firebaseapp.com',
    storageBucket: 'ec-carwash-app.firebasestorage.app',
    measurementId: 'G-X2VCGERMKP',
  );

}